# docker-compose.yml
version: '3.8'
services:
  mysql-post:
    image: mysql:8.0
    container_name: companypulse-mysql-post
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companypulse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-post:/var/lib/mysql
    networks:
      - companypulse-network

  mysql-review:
    image: mysql:8.0
    container_name: companypulse-mysql-review
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companypulse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-review:/var/lib/mysql
    networks:
      - companypulse-network

  mysql-comment:
    image: mysql:8.0
    container_name: companypulse-mysql-comment
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companypulse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql-comment:/var/lib/mysql
    networks:
      - companypulse-network

  mysql-notification:
    image: mysql:8.0
    container_name: companypulse-mysql-notification
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: companypulse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-notification:/var/lib/mysql
    networks:
      - companypulse-network

#  app:
#    build: .
#    container_name: companypulse-app
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/companypulse
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#    networks:
#      - companypulse-network

volumes:
  mysql-post:
  mysql-review:
  mysql-notification:
  mysql-comment:

networks:
  companypulse-network: